data: 'characteristics_us'
data_refine: #'res/predictions/100_characteristics_us' # ! 학습이 끊겼을시 재실행 / 평소에는 None 줄 것!
#data_filter_year : 1990

# 아래 파라미터는 클러스터 6개 기준의 best_params로 설정되었음. (OPTUNA hyper parameter tuning)
model:
  n_bins: 128 # ! bins
  augment_std: 0.05 # ! 재설정
  masking_ratio: 0 # ! 재설정
  cluster_num: 100 # todo 가장 중요한 CLUSTER NUMBER
  # dim_in_out: 64
  num_features: 128 # do not change
  hidden_dim: 128 # ! hiddens
  depth: 6
  heads: 8
  pre_norm: True
  use_simple_rmsnorm: True
  cls_init: "random"

# 오직 100 epochs 훈련은 부족할 수 있음
train:
  model_saving_strategy: "better"
  saving_path: 'res'
  seed: 0
  num_workers: 4
  pin_memory: True
  device: "cuda" 
  epochs: 100
  batch_size: 32 #! 낮은 Batch가 더 좋은 loss를 뽑아 내는 중
  reload: None
  lr: 0.0003
  warmup_steps: 0
  use_accelerator: False
  use_wandb: False
